# Requirements

In [61]:
import numpy as np 
import pandas as pd 
import os

In [62]:
!pip install polars

Requirement already satisfied: polars in /usr/local/lib/python3.10/site-packages (1.32.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [63]:
import polars as pl

In [64]:
import re

# Reading Data

In [65]:
dft = pl.read_parquet('/kaggle/input/aeroclub-recsys-2025/train.parquet')

# Analysis

In [66]:
pl.read_parquet_schema('/kaggle/input/aeroclub-recsys-2025/train.parquet')

Schema([('Id', Int64),
        ('bySelf', Boolean),
        ('companyID', Int64),
        ('corporateTariffCode', Int64),
        ('frequentFlyer', String),
        ('nationality', Int64),
        ('isAccess3D', Boolean),
        ('isVip', Boolean),
        ('legs0_arrivalAt', String),
        ('legs0_departureAt', String),
        ('legs0_duration', String),
        ('legs0_segments0_aircraft_code', String),
        ('legs0_segments0_arrivalTo_airport_city_iata', String),
        ('legs0_segments0_arrivalTo_airport_iata', String),
        ('legs0_segments0_baggageAllowance_quantity', Float64),
        ('legs0_segments0_baggageAllowance_weightMeasurementType', Float64),
        ('legs0_segments0_cabinClass', Float64),
        ('legs0_segments0_departureFrom_airport_iata', String),
        ('legs0_segments0_duration', String),
        ('legs0_segments0_flightNumber', String),
        ('legs0_segments0_marketingCarrier_code', String),
        ('legs0_segments0_operatingCarrier_code', String),
        ('legs0_segments0_seatsAvailable', Float64),
        ('legs0_segments1_aircraft_code', String),
        ('legs0_segments1_arrivalTo_airport_city_iata', String),
        ('legs0_segments1_arrivalTo_airport_iata', String),
        ('legs0_segments1_baggageAllowance_quantity', Float64),
        ('legs0_segments1_baggageAllowance_weightMeasurementType', Float64),
        ('legs0_segments1_cabinClass', Float64),
        ('legs0_segments1_departureFrom_airport_iata', String),
        ('legs0_segments1_duration', String),
        ('legs0_segments1_flightNumber', String),
        ('legs0_segments1_marketingCarrier_code', String),
        ('legs0_segments1_operatingCarrier_code', String),
        ('legs0_segments1_seatsAvailable', Float64),
        ('legs0_segments2_aircraft_code', String),
        ('legs0_segments2_arrivalTo_airport_city_iata', String),
        ('legs0_segments2_arrivalTo_airport_iata', String),
        ('legs0_segments2_baggageAllowance_quantity', Float64),
        ('legs0_segments2_baggageAllowance_weightMeasurementType', Float64),
        ('legs0_segments2_cabinClass', Float64),
        ('legs0_segments2_departureFrom_airport_iata', String),
        ('legs0_segments2_duration', String),
        ('legs0_segments2_flightNumber', String),
        ('legs0_segments2_marketingCarrier_code', String),
        ('legs0_segments2_operatingCarrier_code', String),
        ('legs0_segments2_seatsAvailable', Float64),
        ('legs0_segments3_aircraft_code', String),
        ('legs0_segments3_arrivalTo_airport_city_iata', String),
        ('legs0_segments3_arrivalTo_airport_iata', String),
        ('legs0_segments3_baggageAllowance_quantity', Float64),
        ('legs0_segments3_baggageAllowance_weightMeasurementType', Float64),
        ('legs0_segments3_cabinClass', Float64),
        ('legs0_segments3_departureFrom_airport_iata', String),
        ('legs0_segments3_duration', String),
        ('legs0_segments3_flightNumber', String),
        ('legs0_segments3_marketingCarrier_code', String),
        ('legs0_segments3_operatingCarrier_code', String),
        ('legs0_segments3_seatsAvailable', Float64),
        ('legs1_arrivalAt', String),
        ('legs1_departureAt', String),
        ('legs1_duration', String),
        ('legs1_segments0_aircraft_code', String),
        ('legs1_segments0_arrivalTo_airport_city_iata', String),
        ('legs1_segments0_arrivalTo_airport_iata', String),
        ('legs1_segments0_baggageAllowance_quantity', Float64),
        ('legs1_segments0_baggageAllowance_weightMeasurementType', Float64),
        ('legs1_segments0_cabinClass', Float64),
        ('legs1_segments0_departureFrom_airport_iata', String),
        ('legs1_segments0_duration', String),
        ('legs1_segments0_flightNumber', String),
        ('legs1_segments0_marketingCarrier_code', String),
        ('legs1_segments0_operatingCarrier_code', String),
        ('legs1_segments0_seatsAvailable', Float64),
        ('legs1_segments1_aircraft_code', String),
        ('legs1_segments1_arrivalTo_airport_city_iata', String),
        ('legs1_segments1_arrivalTo_airport_iata', String),
        ('legs1_segments1_baggageAllowance_quantity', Float64),
        ('legs1_segments1_baggageAllowance_weightMeasurementType', Float64),
        ('legs1_segments1_cabinClass', Float64),
        ('legs1_segments1_departureFrom_airport_iata', String),
        ('legs1_segments1_duration', String),
        ('legs1_segments1_flightNumber', String),
        ('legs1_segments1_marketingCarrier_code', String),
        ('legs1_segments1_operatingCarrier_code', String),
        ('legs1_segments1_seatsAvailable', Float64),
        ('legs1_segments2_aircraft_code', String),
        ('legs1_segments2_arrivalTo_airport_city_iata', String),
        ('legs1_segments2_arrivalTo_airport_iata', String),
        ('legs1_segments2_baggageAllowance_quantity', Float64),
        ('legs1_segments2_baggageAllowance_weightMeasurementType', Float64),
        ('legs1_segments2_cabinClass', Float64),
        ('legs1_segments2_departureFrom_airport_iata', String),
        ('legs1_segments2_duration', String),
        ('legs1_segments2_flightNumber', String),
        ('legs1_segments2_marketingCarrier_code', String),
        ('legs1_segments2_operatingCarrier_code', String),
        ('legs1_segments2_seatsAvailable', Float64),
        ('legs1_segments3_aircraft_code', String),
        ('legs1_segments3_arrivalTo_airport_city_iata', String),
        ('legs1_segments3_arrivalTo_airport_iata', String),
        ('legs1_segments3_baggageAllowance_quantity', Float64),
        ('legs1_segments3_baggageAllowance_weightMeasurementType', Float64),
        ('legs1_segments3_cabinClass', Float64),
        ('legs1_segments3_departureFrom_airport_iata', String),
        ('legs1_segments3_duration', String),
        ('legs1_segments3_flightNumber', String),
        ('legs1_segments3_marketingCarrier_code', String),
        ('legs1_segments3_operatingCarrier_code', String),
        ('legs1_segments3_seatsAvailable', Float64),
        ('miniRules0_monetaryAmount', Float64),
        ('miniRules0_percentage', Float64),
        ('miniRules0_statusInfos', Float64),
        ('miniRules1_monetaryAmount', Float64),
        ('miniRules1_percentage', Float64),
        ('miniRules1_statusInfos', Float64),
        ('pricingInfo_isAccessTP', Float64),
        ('pricingInfo_passengerCount', Int64),
        ('profileId', Int64),
        ('ranker_id', String),
        ('requestDate', Datetime(time_unit='ns', time_zone=None)),
        ('searchRoute', String),
        ('sex', Boolean),
        ('taxes', Float64),
        ('totalPrice', Float64),
        ('selected', Int64),
        ('__index_level_0__', Int64)])

In [67]:
dft

shape: (18_145_372, 127)
┌──────────┬────────┬───────────┬──────────────┬───┬────────┬────────────┬──────────┬──────────────┐
│ Id       ┆ bySelf ┆ companyID ┆ corporateTar ┆ … ┆ taxes  ┆ totalPrice ┆ selected ┆ __index_leve │
│ ---      ┆ ---    ┆ ---       ┆ iffCode      ┆   ┆ ---    ┆ ---        ┆ ---      ┆ l_0__        │
│ i64      ┆ bool   ┆ i64       ┆ ---          ┆   ┆ f64    ┆ f64        ┆ i64      ┆ ---          │
│          ┆        ┆           ┆ i64          ┆   ┆        ┆            ┆          ┆ i64          │
╞══════════╪════════╪═══════════╪══════════════╪═══╪════════╪════════════╪══════════╪══════════════╡
│ 0        ┆ true   ┆ 57323     ┆ null         ┆ … ┆ 370.0  ┆ 16884.0    ┆ 1        ┆ 0            │
│ 1        ┆ true   ┆ 57323     ┆ 123          ┆ … ┆ 2240.0 ┆ 51125.0    ┆ 0        ┆ 1            │
│ 2        ┆ true   ┆ 57323     ┆ null         ┆ … ┆ 2240.0 ┆ 53695.0    ┆ 0        ┆ 2            │
│ 3        ┆ true   ┆ 57323     ┆ 123          ┆ … ┆ 2240.0 ┆ 81880.0    ┆ 0        ┆ 3            │
│ 4        ┆ true   ┆ 57323     ┆ null         ┆ … ┆ 2240.0 ┆ 86070.0    ┆ 0        ┆ 4            │
│ …        ┆ …      ┆ …         ┆ …            ┆ … ┆ …      ┆ …          ┆ …        ┆ …            │
│ 18146427 ┆ true   ┆ 54154     ┆ 44           ┆ … ┆ 5560.0 ┆ 30730.0    ┆ 0        ┆ 18146427     │
│ 18146428 ┆ true   ┆ 54154     ┆ 44           ┆ … ┆ 5560.0 ┆ 27660.0    ┆ 0        ┆ 18146428     │
│ 18146429 ┆ true   ┆ 54154     ┆ 44           ┆ … ┆ 5460.0 ┆ 24460.0    ┆ 0        ┆ 18146429     │
│ 18146430 ┆ true   ┆ 54154     ┆ 44           ┆ … ┆ 5560.0 ┆ 25360.0    ┆ 0        ┆ 18146430     │
│ 18146431 ┆ true   ┆ 54154     ┆ 44           ┆ … ┆ 5460.0 ┆ 22160.0    ┆ 0        ┆ 18146431     │
└──────────┴────────┴───────────┴──────────────┴───┴────────┴────────────┴──────────┴──────────────┘

# Cleaning Data & Feature Engineering

In [68]:
dft= dft.drop('bySelf','sex','legs0_segments0_cabinClass','nationality','legs0_segments0_marketingCarrier_code','legs0_segments2_marketingCarrier_code','legs0_segments3_marketingCarrier_code','legs1_segments0_marketingCarrier_code','legs1_segments2_marketingCarrier_code','legs1_segments3_marketingCarrier_code')

In [69]:
dft = dft.drop('legs1_segments0_duration')

In [70]:
dft = dft.with_columns(
    TotalPrice = pl.col("totalPrice") + pl.col("taxes"))

In [71]:
dft['TotalPrice']

shape: (18_145_372,)
Series: 'TotalPrice' [f64]
[
	17254.0
	53365.0
	55935.0
	84120.0
	88310.0
	…
	36290.0
	33220.0
	29920.0
	30920.0
	27620.0
]

In [72]:
dft = dft.drop('legs0_segments0_duration','legs0_segments1_duration','legs0_segments2_duration','legs0_segments3_duration')

In [73]:
dft = dft.drop('legs1_segments1_duration','legs1_segments2_duration','legs1_segments3_duration')

In [74]:
dft['legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration']

shape: (18_145_372, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ legs0_departur ┆ legs0_arrivalA ┆ legs0_duration ┆ legs1_departu ┆ legs1_arrival ┆ legs1_duratio │
│ eAt            ┆ t              ┆ ---            ┆ reAt          ┆ At            ┆ n             │
│ ---            ┆ ---            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ str            ┆                ┆ str           ┆ str           ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2024-06-15T15: ┆ 2024-06-15T16: ┆ 02:40:00       ┆ 2024-07-09T09 ┆ 2024-07-09T14 ┆ 02:35:00      │
│ 40:00          ┆ 20:00          ┆                ┆ :45:00        ┆ :20:00        ┆               │
│ 2024-06-15T09: ┆ 2024-06-15T14: ┆ 07:25:00       ┆ 2024-07-09T22 ┆ 2024-07-10T08 ┆ 08:25:00      │
│ 25:00          ┆ 50:00          ┆                ┆ :05:00        ┆ :30:00        ┆               │
│ 2024-06-15T09: ┆ 2024-06-15T14: ┆ 07:25:00       ┆ 2024-07-09T22 ┆ 2024-07-10T08 ┆ 08:25:00      │
│ 25:00          ┆ 50:00          ┆                ┆ :05:00        ┆ :30:00        ┆               │
│ 2024-06-15T09: ┆ 2024-06-15T14: ┆ 07:25:00       ┆ 2024-07-09T22 ┆ 2024-07-10T08 ┆ 08:25:00      │
│ 25:00          ┆ 50:00          ┆                ┆ :05:00        ┆ :30:00        ┆               │
│ 2024-06-15T09: ┆ 2024-06-15T14: ┆ 07:25:00       ┆ 2024-07-09T22 ┆ 2024-07-10T08 ┆ 08:25:00      │
│ 25:00          ┆ 50:00          ┆                ┆ :05:00        ┆ :30:00        ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2024-11-05T20: ┆ 2024-11-06T09: ┆ 10:55:00       ┆ 2024-11-09T19 ┆ 2024-11-10T08 ┆ 14:45:00      │
│ 50:00          ┆ 45:00          ┆                ┆ :25:00        ┆ :10:00        ┆               │
│ 2024-11-05T00: ┆ 2024-11-05T20: ┆ 17:40:00       ┆ 2024-11-09T21 ┆ 2024-11-10T08 ┆ 13:25:00      │
│ 20:00          ┆ 00:00          ┆                ┆ :10:00        ┆ :35:00        ┆               │
│ 2024-11-05T00: ┆ 2024-11-05T20: ┆ 17:40:00       ┆ 2024-11-09T19 ┆ 2024-11-10T08 ┆ 14:45:00      │
│ 20:00          ┆ 00:00          ┆                ┆ :25:00        ┆ :10:00        ┆               │
│ 2024-11-05T19: ┆ 2024-11-06T17: ┆ 19:40:00       ┆ 2024-11-09T21 ┆ 2024-11-10T08 ┆ 13:25:00      │
│ 30:00          ┆ 10:00          ┆                ┆ :10:00        ┆ :35:00        ┆               │
│ 2024-11-05T19: ┆ 2024-11-06T17: ┆ 19:40:00       ┆ 2024-11-09T19 ┆ 2024-11-10T08 ┆ 14:45:00      │
│ 30:00          ┆ 10:00          ┆                ┆ :25:00        ┆ :10:00        ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [75]:
dft= dft.with_columns(
    pl.col('legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration').str.replace(r"T", "  "))

In [76]:
dft['legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration']

shape: (18_145_372, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ legs0_departur ┆ legs0_arrivalA ┆ legs0_duration ┆ legs1_departu ┆ legs1_arrival ┆ legs1_duratio │
│ eAt            ┆ t              ┆ ---            ┆ reAt          ┆ At            ┆ n             │
│ ---            ┆ ---            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ str            ┆                ┆ str           ┆ str           ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2024-06-15     ┆ 2024-06-15     ┆ 02:40:00       ┆ 2024-07-09    ┆ 2024-07-09    ┆ 02:35:00      │
│ 15:40:00       ┆ 16:20:00       ┆                ┆ 09:45:00      ┆ 14:20:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2024-11-05     ┆ 2024-11-06     ┆ 10:55:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 14:45:00      │
│ 20:50:00       ┆ 09:45:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
│ 2024-11-05     ┆ 2024-11-05     ┆ 17:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 13:25:00      │
│ 00:20:00       ┆ 20:00:00       ┆                ┆ 21:10:00      ┆ 08:35:00      ┆               │
│ 2024-11-05     ┆ 2024-11-05     ┆ 17:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 14:45:00      │
│ 00:20:00       ┆ 20:00:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
│ 2024-11-05     ┆ 2024-11-06     ┆ 19:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 13:25:00      │
│ 19:30:00       ┆ 17:10:00       ┆                ┆ 21:10:00      ┆ 08:35:00      ┆               │
│ 2024-11-05     ┆ 2024-11-06     ┆ 19:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 14:45:00      │
│ 19:30:00       ┆ 17:10:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [77]:
dft= dft.with_columns(
    pl.col('legs0_departureAt',
'legs0_arrivalAt',
'legs1_departureAt',
'legs1_arrivalAt').str.to_datetime("%Y-%m-%d %H:%M:%S"))

In [78]:
dft['legs0_departureAt',
'legs0_arrivalAt',
'legs1_departureAt',
'legs1_arrivalAt']

shape: (18_145_372, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┐
│ legs0_departureAt   ┆ legs0_arrivalAt     ┆ legs1_departureAt   ┆ legs1_arrivalAt     │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════╪═════════════════════╪═════════════════════╪═════════════════════╡
│ 2024-06-15 15:40:00 ┆ 2024-06-15 16:20:00 ┆ 2024-07-09 09:45:00 ┆ 2024-07-09 14:20:00 │
│ 2024-06-15 09:25:00 ┆ 2024-06-15 14:50:00 ┆ 2024-07-09 22:05:00 ┆ 2024-07-10 08:30:00 │
│ 2024-06-15 09:25:00 ┆ 2024-06-15 14:50:00 ┆ 2024-07-09 22:05:00 ┆ 2024-07-10 08:30:00 │
│ 2024-06-15 09:25:00 ┆ 2024-06-15 14:50:00 ┆ 2024-07-09 22:05:00 ┆ 2024-07-10 08:30:00 │
│ 2024-06-15 09:25:00 ┆ 2024-06-15 14:50:00 ┆ 2024-07-09 22:05:00 ┆ 2024-07-10 08:30:00 │
│ …                   ┆ …                   ┆ …                   ┆ …                   │
│ 2024-11-05 20:50:00 ┆ 2024-11-06 09:45:00 ┆ 2024-11-09 19:25:00 ┆ 2024-11-10 08:10:00 │
│ 2024-11-05 00:20:00 ┆ 2024-11-05 20:00:00 ┆ 2024-11-09 21:10:00 ┆ 2024-11-10 08:35:00 │
│ 2024-11-05 00:20:00 ┆ 2024-11-05 20:00:00 ┆ 2024-11-09 19:25:00 ┆ 2024-11-10 08:10:00 │
│ 2024-11-05 19:30:00 ┆ 2024-11-06 17:10:00 ┆ 2024-11-09 21:10:00 ┆ 2024-11-10 08:35:00 │
│ 2024-11-05 19:30:00 ┆ 2024-11-06 17:10:00 ┆ 2024-11-09 19:25:00 ┆ 2024-11-10 08:10:00 │
└─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┘

In [79]:
dft['legs0_duration',
'legs1_duration']

shape: (18_145_372, 2)
┌────────────────┬────────────────┐
│ legs0_duration ┆ legs1_duration │
│ ---            ┆ ---            │
│ str            ┆ str            │
╞════════════════╪════════════════╡
│ 02:40:00       ┆ 02:35:00       │
│ 07:25:00       ┆ 08:25:00       │
│ 07:25:00       ┆ 08:25:00       │
│ 07:25:00       ┆ 08:25:00       │
│ 07:25:00       ┆ 08:25:00       │
│ …              ┆ …              │
│ 10:55:00       ┆ 14:45:00       │
│ 17:40:00       ┆ 13:25:00       │
│ 17:40:00       ┆ 14:45:00       │
│ 19:40:00       ┆ 13:25:00       │
│ 19:40:00       ┆ 14:45:00       │
└────────────────┴────────────────┘

In [80]:
dft = dft.with_columns(
    pl.col('legs0_duration',
'legs1_duration').str.replace_all(r"\.\d{2}", "")
)

In [81]:
dft=dft.with_columns(
    pl.col('legs0_duration',
'legs1_duration').str.to_time("%H:%M:%S"))

In [82]:
dft['legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration']

shape: (18_145_372, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ legs0_departur ┆ legs0_arrivalA ┆ legs0_duration ┆ legs1_departu ┆ legs1_arrival ┆ legs1_duratio │
│ eAt            ┆ t              ┆ ---            ┆ reAt          ┆ At            ┆ n             │
│ ---            ┆ ---            ┆ time           ┆ ---           ┆ ---           ┆ ---           │
│ datetime[μs]   ┆ datetime[μs]   ┆                ┆ datetime[μs]  ┆ datetime[μs]  ┆ time          │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2024-06-15     ┆ 2024-06-15     ┆ 02:40:00       ┆ 2024-07-09    ┆ 2024-07-09    ┆ 02:35:00      │
│ 15:40:00       ┆ 16:20:00       ┆                ┆ 09:45:00      ┆ 14:20:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ 07:25:00       ┆ 2024-07-09    ┆ 2024-07-10    ┆ 08:25:00      │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2024-11-05     ┆ 2024-11-06     ┆ 10:55:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 14:45:00      │
│ 20:50:00       ┆ 09:45:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
│ 2024-11-05     ┆ 2024-11-05     ┆ 17:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 13:25:00      │
│ 00:20:00       ┆ 20:00:00       ┆                ┆ 21:10:00      ┆ 08:35:00      ┆               │
│ 2024-11-05     ┆ 2024-11-05     ┆ 17:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 14:45:00      │
│ 00:20:00       ┆ 20:00:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
│ 2024-11-05     ┆ 2024-11-06     ┆ 19:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 13:25:00      │
│ 19:30:00       ┆ 17:10:00       ┆                ┆ 21:10:00      ┆ 08:35:00      ┆               │
│ 2024-11-05     ┆ 2024-11-06     ┆ 19:40:00       ┆ 2024-11-09    ┆ 2024-11-10    ┆ 14:45:00      │
│ 19:30:00       ┆ 17:10:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [83]:
dftt = pl.read_parquet('/kaggle/input/aeroclub-recsys-2025/test.parquet')

In [84]:
dftt= dftt.drop('bySelf','sex','legs0_segments0_cabinClass','nationality','legs0_segments0_marketingCarrier_code','legs0_segments2_marketingCarrier_code','legs0_segments3_marketingCarrier_code','legs1_segments0_marketingCarrier_code','legs1_segments2_marketingCarrier_code','legs1_segments3_marketingCarrier_code',)

In [85]:
dftt = dftt.with_columns(
    TotalPrice = pl.col("totalPrice") + pl.col("taxes"))

In [86]:
dftt = dftt.drop('legs1_segments0_duration')

In [87]:
dftt = dftt.drop('legs0_segments0_duration','legs0_segments1_duration','legs0_segments2_duration','legs0_segments3_duration')

In [88]:
dftt = dftt.drop('legs1_segments1_duration','legs1_segments2_duration','legs1_segments3_duration')

In [89]:
dftt['legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration']

shape: (6_897_776, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ legs0_departur ┆ legs0_arrivalA ┆ legs0_duration ┆ legs1_departu ┆ legs1_arrival ┆ legs1_duratio │
│ eAt            ┆ t              ┆ ---            ┆ reAt          ┆ At            ┆ n             │
│ ---            ┆ ---            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ str            ┆                ┆ str           ┆ str           ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2024-12-19T06: ┆ 2024-12-19T11: ┆ 02:30:00       ┆ 2024-12-21T21 ┆ 2024-12-21T21 ┆ 02:45:00      │
│ 50:00          ┆ 20:00          ┆                ┆ :10:00        ┆ :55:00        ┆               │
│ 2024-12-19T06: ┆ 2024-12-19T11: ┆ 02:30:00       ┆ 2024-12-21T21 ┆ 2024-12-21T21 ┆ 02:45:00      │
│ 50:00          ┆ 20:00          ┆                ┆ :10:00        ┆ :55:00        ┆               │
│ 2024-12-19T06: ┆ 2024-12-19T11: ┆ 02:30:00       ┆ 2024-12-21T21 ┆ 2024-12-21T21 ┆ 02:45:00      │
│ 50:00          ┆ 20:00          ┆                ┆ :10:00        ┆ :55:00        ┆               │
│ 2024-12-19T08: ┆ 2024-12-19T12: ┆ 02:20:00       ┆ 2024-12-21T12 ┆ 2024-12-21T12 ┆ 02:35:00      │
│ 25:00          ┆ 45:00          ┆                ┆ :00:00        ┆ :35:00        ┆               │
│ 2024-12-19T08: ┆ 2024-12-19T12: ┆ 02:20:00       ┆ 2024-12-21T12 ┆ 2024-12-21T12 ┆ 02:35:00      │
│ 25:00          ┆ 45:00          ┆                ┆ :00:00        ┆ :35:00        ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2025-01-08T09: ┆ 2025-01-08T12: ┆ 02:45:00       ┆ null          ┆ null          ┆ null          │
│ 05:00          ┆ 50:00          ┆                ┆               ┆               ┆               │
│ 2025-01-08T21: ┆ 2025-01-09T01: ┆ 02:45:00       ┆ null          ┆ null          ┆ null          │
│ 25:00          ┆ 10:00          ┆                ┆               ┆               ┆               │
│ 2025-01-08T21: ┆ 2025-01-09T01: ┆ 02:45:00       ┆ null          ┆ null          ┆ null          │
│ 25:00          ┆ 10:00          ┆                ┆               ┆               ┆               │
│ 2025-01-08T15: ┆ 2025-01-08T18: ┆ 02:40:00       ┆ null          ┆ null          ┆ null          │
│ 10:00          ┆ 50:00          ┆                ┆               ┆               ┆               │
│ 2025-01-08T15: ┆ 2025-01-08T18: ┆ 02:40:00       ┆ null          ┆ null          ┆ null          │
│ 10:00          ┆ 50:00          ┆                ┆               ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [90]:
dftt= dftt.with_columns(
    pl.col('legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration').str.replace(r"T", "  "))

In [91]:
dftt= dftt.with_columns(
    pl.col('legs0_departureAt',
'legs0_arrivalAt',
'legs1_departureAt',
'legs1_arrivalAt').str.to_datetime("%Y-%m-%d %H:%M:%S"))

In [92]:
dftt = dftt.with_columns(
    pl.col('legs0_duration',
'legs1_duration').str.replace_all(r"\.\d{2}", "")
)

In [93]:
dftt=dftt.with_columns(
    pl.col('legs0_duration',
'legs1_duration').str.to_time("%H:%M:%S"))

In [94]:
dftt['legs0_departureAt',
'legs0_arrivalAt',
'legs0_duration',
'legs1_departureAt',
'legs1_arrivalAt',
'legs1_duration']

shape: (6_897_776, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ legs0_departur ┆ legs0_arrivalA ┆ legs0_duration ┆ legs1_departu ┆ legs1_arrival ┆ legs1_duratio │
│ eAt            ┆ t              ┆ ---            ┆ reAt          ┆ At            ┆ n             │
│ ---            ┆ ---            ┆ time           ┆ ---           ┆ ---           ┆ ---           │
│ datetime[μs]   ┆ datetime[μs]   ┆                ┆ datetime[μs]  ┆ datetime[μs]  ┆ time          │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2024-12-19     ┆ 2024-12-19     ┆ 02:30:00       ┆ 2024-12-21    ┆ 2024-12-21    ┆ 02:45:00      │
│ 06:50:00       ┆ 11:20:00       ┆                ┆ 21:10:00      ┆ 21:55:00      ┆               │
│ 2024-12-19     ┆ 2024-12-19     ┆ 02:30:00       ┆ 2024-12-21    ┆ 2024-12-21    ┆ 02:45:00      │
│ 06:50:00       ┆ 11:20:00       ┆                ┆ 21:10:00      ┆ 21:55:00      ┆               │
│ 2024-12-19     ┆ 2024-12-19     ┆ 02:30:00       ┆ 2024-12-21    ┆ 2024-12-21    ┆ 02:45:00      │
│ 06:50:00       ┆ 11:20:00       ┆                ┆ 21:10:00      ┆ 21:55:00      ┆               │
│ 2024-12-19     ┆ 2024-12-19     ┆ 02:20:00       ┆ 2024-12-21    ┆ 2024-12-21    ┆ 02:35:00      │
│ 08:25:00       ┆ 12:45:00       ┆                ┆ 12:00:00      ┆ 12:35:00      ┆               │
│ 2024-12-19     ┆ 2024-12-19     ┆ 02:20:00       ┆ 2024-12-21    ┆ 2024-12-21    ┆ 02:35:00      │
│ 08:25:00       ┆ 12:45:00       ┆                ┆ 12:00:00      ┆ 12:35:00      ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2025-01-08     ┆ 2025-01-08     ┆ 02:45:00       ┆ null          ┆ null          ┆ null          │
│ 09:05:00       ┆ 12:50:00       ┆                ┆               ┆               ┆               │
│ 2025-01-08     ┆ 2025-01-09     ┆ 02:45:00       ┆ null          ┆ null          ┆ null          │
│ 21:25:00       ┆ 01:10:00       ┆                ┆               ┆               ┆               │
│ 2025-01-08     ┆ 2025-01-09     ┆ 02:45:00       ┆ null          ┆ null          ┆ null          │
│ 21:25:00       ┆ 01:10:00       ┆                ┆               ┆               ┆               │
│ 2025-01-08     ┆ 2025-01-08     ┆ 02:40:00       ┆ null          ┆ null          ┆ null          │
│ 15:10:00       ┆ 18:50:00       ┆                ┆               ┆               ┆               │
│ 2025-01-08     ┆ 2025-01-08     ┆ 02:40:00       ┆ null          ┆ null          ┆ null          │
│ 15:10:00       ┆ 18:50:00       ┆                ┆               ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [95]:
def preprocess(df: pl.DataFrame) -> pl.DataFrame:
    datetime_cols = ["legs0_departureAt", "legs0_arrivalAt",
                     "legs1_departureAt", "legs1_arrivalAt"]

    for col in datetime_cols:
        # Ensure datetime type
        df = df.with_columns(
            pl.col(col).cast(pl.Datetime(time_unit="us"))
        )

        # Basic datetime features
        df = df.with_columns([
            pl.col(col).dt.hour().alias(f"{col}_hour"),
            pl.col(col).dt.weekday().alias(f"{col}_dow"),
            pl.col(col).dt.month().alias(f"{col}_month"),
            (pl.col(col).dt.weekday() >= 5).cast(pl.Int8).alias(f"{col}_is_weekend"),
        ])

        # Cyclical hour encoding
        df = df.with_columns([
            (pl.col(f"{col}_hour") * (2 * np.pi) / 24).sin().alias(f"{col}_hour_sin"),
            (pl.col(f"{col}_hour") * (2 * np.pi) / 24).cos().alias(f"{col}_hour_cos"),
        ])

    # Duration to minutes
    duration_cols = ["legs0_duration", "legs1_duration"]
    for col in duration_cols:
    # If already a Duration, just convert to minutes
        if df[col].dtype == pl.Duration(time_unit="us"):
            df = df.with_columns(
                (pl.col(col).dt.seconds() / 60).alias(col)
            )
        # If it's a Time (HH:MM:SS)
        elif df[col].dtype == pl.Time:
            df = df.with_columns(
                (pl.col(col).dt.hour() * 60 +
                 pl.col(col).dt.minute() +
                 pl.col(col).dt.second() / 60).alias(col)
            )
        # If it's a string like "02:40:00"
        else:
            df = df.with_columns(
                (pl.col(col).str.strptime(pl.Time, "%H:%M:%S", strict=False).dt.hour() * 60 +
                 pl.col(col).str.strptime(pl.Time, "%H:%M:%S", strict=False).dt.minute() +
                 pl.col(col).str.strptime(pl.Time, "%H:%M:%S", strict=False).dt.second() / 60
                ).alias(col)
            )
   
    return df

In [96]:
print("Preprocessing...")
dft = preprocess(dft)
dftt = preprocess(dftt)

Preprocessing...

# Feature Selection

In [97]:
x = dft['Id','TotalPrice','searchRoute','corporateTariffCode','profileId','companyID',
'legs0_duration' ,
'legs1_duration','legs0_segments0_seatsAvailable','legs0_segments1_seatsAvailable','legs1_segments0_seatsAvailable','legs1_segments1_seatsAvailable',
'miniRules0_monetaryAmount' ,
'miniRules0_percentage',
'miniRules0_statusInfos' ,
'miniRules1_monetaryAmount' ,
'miniRules1_percentage' ,
'miniRules1_statusInfos' ,
'pricingInfo_isAccessTP' ,
'pricingInfo_passengerCount','legs0_segments0_baggageAllowance_quantity','legs0_segments1_baggageAllowance_quantity','legs1_segments0_baggageAllowance_quantity','legs1_segments1_baggageAllowance_quantity',
'legs0_segments0_arrivalTo_airport_iata','legs0_segments1_arrivalTo_airport_iata',
'legs1_segments0_arrivalTo_airport_iata','legs1_segments1_arrivalTo_airport_iata',
'legs0_segments0_arrivalTo_airport_city_iata','legs0_segments1_arrivalTo_airport_city_iata',
'legs1_segments0_arrivalTo_airport_city_iata','legs1_segments1_arrivalTo_airport_city_iata']

In [98]:
string_columns = [col_name for col_name, dtype in zip(x.columns, x.dtypes) if dtype == pl.Utf8]
print(string_columns)

['searchRoute', 'legs0_segments0_arrivalTo_airport_iata', 'legs0_segments1_arrivalTo_airport_iata', 'legs1_segments0_arrivalTo_airport_iata', 'legs1_segments1_arrivalTo_airport_iata', 'legs0_segments0_arrivalTo_airport_city_iata', 'legs0_segments1_arrivalTo_airport_city_iata', 'legs1_segments0_arrivalTo_airport_city_iata', 'legs1_segments1_arrivalTo_airport_city_iata']

In [99]:
CATEGORICAL_COLS = ['searchRoute', 'legs0_segments0_arrivalTo_airport_iata', 'legs0_segments1_arrivalTo_airport_iata', 'legs1_segments0_arrivalTo_airport_iata', 'legs1_segments1_arrivalTo_airport_iata',  'legs0_segments0_arrivalTo_airport_city_iata', 'legs0_segments1_arrivalTo_airport_city_iata', 'legs1_segments0_arrivalTo_airport_city_iata', 'legs1_segments1_arrivalTo_airport_city_iata']

In [100]:
xt = dftt['Id','TotalPrice','searchRoute','corporateTariffCode','profileId','companyID',
'legs0_duration' ,
'legs1_duration','legs0_segments0_seatsAvailable','legs0_segments1_seatsAvailable','legs1_segments0_seatsAvailable','legs1_segments1_seatsAvailable',
'miniRules0_monetaryAmount' ,
'miniRules0_percentage',
'miniRules0_statusInfos' ,
'miniRules1_monetaryAmount' ,
'miniRules1_percentage' ,
'miniRules1_statusInfos' ,
'pricingInfo_isAccessTP' ,
'pricingInfo_passengerCount','legs0_segments0_baggageAllowance_quantity','legs0_segments1_baggageAllowance_quantity','legs1_segments0_baggageAllowance_quantity','legs1_segments1_baggageAllowance_quantity',
'legs0_segments0_arrivalTo_airport_iata','legs0_segments1_arrivalTo_airport_iata',
'legs1_segments0_arrivalTo_airport_iata','legs1_segments1_arrivalTo_airport_iata',
'legs0_segments0_arrivalTo_airport_city_iata','legs0_segments1_arrivalTo_airport_city_iata',
'legs1_segments0_arrivalTo_airport_city_iata','legs1_segments1_arrivalTo_airport_city_iata']

In [101]:
dft['legs0_departureAt',
 'legs0_arrivalAt',
 'legs0_duration',
 'legs1_departureAt',
 'legs1_arrivalAt',
 'legs1_duration']

shape: (18_145_372, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ legs0_departur ┆ legs0_arrivalA ┆ legs0_duration ┆ legs1_departu ┆ legs1_arrival ┆ legs1_duratio │
│ eAt            ┆ t              ┆ ---            ┆ reAt          ┆ At            ┆ n             │
│ ---            ┆ ---            ┆ f64            ┆ ---           ┆ ---           ┆ ---           │
│ datetime[μs]   ┆ datetime[μs]   ┆                ┆ datetime[μs]  ┆ datetime[μs]  ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2024-06-15     ┆ 2024-06-15     ┆ -96.0          ┆ 2024-07-09    ┆ 2024-07-09    ┆ -101.0        │
│ 15:40:00       ┆ 16:20:00       ┆                ┆ 09:45:00      ┆ 14:20:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ -67.0          ┆ 2024-07-09    ┆ 2024-07-10    ┆ -7.0          │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ -67.0          ┆ 2024-07-09    ┆ 2024-07-10    ┆ -7.0          │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ -67.0          ┆ 2024-07-09    ┆ 2024-07-10    ┆ -7.0          │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ 2024-06-15     ┆ 2024-06-15     ┆ -67.0          ┆ 2024-07-09    ┆ 2024-07-10    ┆ -7.0          │
│ 09:25:00       ┆ 14:50:00       ┆                ┆ 22:05:00      ┆ 08:30:00      ┆               │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2024-11-05     ┆ 2024-11-06     ┆ -113.0         ┆ 2024-11-09    ┆ 2024-11-10    ┆ 117.0         │
│ 20:50:00       ┆ 09:45:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
│ 2024-11-05     ┆ 2024-11-05     ┆ 36.0           ┆ 2024-11-09    ┆ 2024-11-10    ┆ 37.0          │
│ 00:20:00       ┆ 20:00:00       ┆                ┆ 21:10:00      ┆ 08:35:00      ┆               │
│ 2024-11-05     ┆ 2024-11-05     ┆ 36.0           ┆ 2024-11-09    ┆ 2024-11-10    ┆ 117.0         │
│ 00:20:00       ┆ 20:00:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
│ 2024-11-05     ┆ 2024-11-06     ┆ -100.0         ┆ 2024-11-09    ┆ 2024-11-10    ┆ 37.0          │
│ 19:30:00       ┆ 17:10:00       ┆                ┆ 21:10:00      ┆ 08:35:00      ┆               │
│ 2024-11-05     ┆ 2024-11-06     ┆ -100.0         ┆ 2024-11-09    ┆ 2024-11-10    ┆ 117.0         │
│ 19:30:00       ┆ 17:10:00       ┆                ┆ 19:25:00      ┆ 08:10:00      ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [102]:
dft = dft.with_columns(
    pl.col("legs1_duration","legs0_duration").abs()
)

In [103]:
dftt = dftt.with_columns(
    pl.col("legs1_duration","legs0_duration").abs()
)

In [104]:
x

shape: (18_145_372, 32)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Id       ┆ TotalPric ┆ searchRou ┆ corporate ┆ … ┆ legs0_seg ┆ legs0_seg ┆ legs1_seg ┆ legs1_seg │
│ ---      ┆ e         ┆ te        ┆ TariffCod ┆   ┆ ments0_ar ┆ ments1_ar ┆ ments0_ar ┆ ments1_ar │
│ i64      ┆ ---       ┆ ---       ┆ e         ┆   ┆ rivalTo_a ┆ rivalTo_a ┆ rivalTo_a ┆ rivalTo_a │
│          ┆ f64       ┆ str       ┆ ---       ┆   ┆ irp…      ┆ irp…      ┆ irp…      ┆ irp…      │
│          ┆           ┆           ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 17254.0   ┆ TLKKJA/KJ ┆ null      ┆ … ┆ KJA       ┆ null      ┆ TLK       ┆ null      │
│          ┆           ┆ ATLK      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 53365.0   ┆ TLKKJA/KJ ┆ 123       ┆ … ┆ OVB       ┆ KJA       ┆ OVB       ┆ TLK       │
│          ┆           ┆ ATLK      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 55935.0   ┆ TLKKJA/KJ ┆ null      ┆ … ┆ OVB       ┆ KJA       ┆ OVB       ┆ TLK       │
│          ┆           ┆ ATLK      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 84120.0   ┆ TLKKJA/KJ ┆ 123       ┆ … ┆ OVB       ┆ KJA       ┆ OVB       ┆ TLK       │
│          ┆           ┆ ATLK      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 88310.0   ┆ TLKKJA/KJ ┆ null      ┆ … ┆ OVB       ┆ KJA       ┆ OVB       ┆ TLK       │
│          ┆           ┆ ATLK      ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 18146427 ┆ 36290.0   ┆ MOWSVX/SV ┆ 44        ┆ … ┆ SGC       ┆ SVX       ┆ UFA       ┆ MOW       │
│          ┆           ┆ XMOW      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 18146428 ┆ 33220.0   ┆ MOWSVX/SV ┆ 44        ┆ … ┆ UFA       ┆ SVX       ┆ SGC       ┆ MOW       │
│          ┆           ┆ XMOW      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 18146429 ┆ 29920.0   ┆ MOWSVX/SV ┆ 44        ┆ … ┆ UFA       ┆ SVX       ┆ UFA       ┆ MOW       │
│          ┆           ┆ XMOW      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 18146430 ┆ 30920.0   ┆ MOWSVX/SV ┆ 44        ┆ … ┆ KUF       ┆ SVX       ┆ SGC       ┆ MOW       │
│          ┆           ┆ XMOW      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 18146431 ┆ 27620.0   ┆ MOWSVX/SV ┆ 44        ┆ … ┆ KUF       ┆ SVX       ┆ UFA       ┆ MOW       │
│          ┆           ┆ XMOW      ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [128]:
dft = dft.with_columns([
    pl.col(c).cast(pl.Categorical).to_physical().alias(c)
    for c in dft.columns if dft.schema[c] == pl.Utf8
])

In [129]:
dftt = dftt.with_columns([
    pl.col(c).cast(pl.Categorical).to_physical().alias(c)
    for c in dftt.columns if dftt.schema[c] == pl.Utf8
])

In [107]:
x

shape: (18_145_372, 32)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Id       ┆ TotalPric ┆ searchRou ┆ corporate ┆ … ┆ legs0_seg ┆ legs0_seg ┆ legs1_seg ┆ legs1_seg │
│ ---      ┆ e         ┆ te        ┆ TariffCod ┆   ┆ ments0_ar ┆ ments1_ar ┆ ments0_ar ┆ ments1_ar │
│ i64      ┆ ---       ┆ ---       ┆ e         ┆   ┆ rivalTo_a ┆ rivalTo_a ┆ rivalTo_a ┆ rivalTo_a │
│          ┆ f64       ┆ u32       ┆ ---       ┆   ┆ irp…      ┆ irp…      ┆ irp…      ┆ irp…      │
│          ┆           ┆           ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 17254.0   ┆ 177       ┆ null      ┆ … ┆ 0         ┆ null      ┆ 66        ┆ null      │
│ 1        ┆ 53365.0   ┆ 177       ┆ 123       ┆ … ┆ 5         ┆ 0         ┆ 5         ┆ 66        │
│ 2        ┆ 55935.0   ┆ 177       ┆ null      ┆ … ┆ 5         ┆ 0         ┆ 5         ┆ 66        │
│ 3        ┆ 84120.0   ┆ 177       ┆ 123       ┆ … ┆ 5         ┆ 0         ┆ 5         ┆ 66        │
│ 4        ┆ 88310.0   ┆ 177       ┆ null      ┆ … ┆ 5         ┆ 0         ┆ 5         ┆ 66        │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 18146427 ┆ 36290.0   ┆ 182       ┆ 44        ┆ … ┆ 28        ┆ 29        ┆ 13        ┆ 11        │
│ 18146428 ┆ 33220.0   ┆ 182       ┆ 44        ┆ … ┆ 13        ┆ 29        ┆ 28        ┆ 11        │
│ 18146429 ┆ 29920.0   ┆ 182       ┆ 44        ┆ … ┆ 13        ┆ 29        ┆ 13        ┆ 11        │
│ 18146430 ┆ 30920.0   ┆ 182       ┆ 44        ┆ … ┆ 31        ┆ 29        ┆ 28        ┆ 11        │
│ 18146431 ┆ 27620.0   ┆ 182       ┆ 44        ┆ … ┆ 31        ┆ 29        ┆ 13        ┆ 11        │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [108]:
y = dft['selected']

In [109]:
y

shape: (18_145_372,)
Series: 'selected' [i64]
[
	1
	0
	0
	0
	0
	…
	0
	0
	0
	0
	0
]

In [110]:
x = x.drop('miniRules0_percentage','miniRules1_percentage')

In [111]:
xt = xt.drop('miniRules0_percentage','miniRules1_percentage')

In [117]:
x.columns

['Id',
 'TotalPrice',
 'searchRoute',
 'corporateTariffCode',
 'profileId',
 'companyID',
 'legs0_duration',
 'legs1_duration',
 'legs0_segments0_seatsAvailable',
 'legs0_segments1_seatsAvailable',
 'legs1_segments0_seatsAvailable',
 'legs1_segments1_seatsAvailable',
 'miniRules0_monetaryAmount',
 'miniRules0_statusInfos',
 'miniRules1_monetaryAmount',
 'miniRules1_statusInfos',
 'pricingInfo_isAccessTP',
 'pricingInfo_passengerCount',
 'legs0_segments0_baggageAllowance_quantity',
 'legs0_segments1_baggageAllowance_quantity',
 'legs1_segments0_baggageAllowance_quantity',
 'legs1_segments1_baggageAllowance_quantity',
 'legs0_segments0_arrivalTo_airport_iata',
 'legs0_segments1_arrivalTo_airport_iata',
 'legs1_segments0_arrivalTo_airport_iata',
 'legs1_segments1_arrivalTo_airport_iata',
 'legs0_segments0_arrivalTo_airport_city_iata',
 'legs0_segments1_arrivalTo_airport_city_iata',
 'legs1_segments0_arrivalTo_airport_city_iata',
 'legs1_segments1_arrivalTo_airport_city_iata']

# Trainig Model

In [112]:
!pip install implicit
!pip install scipy

Collecting implicit
  Downloading implicit-0.7.2-cp310-cp310-manylinux2014_x86_64.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 30.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.10/site-packages (from implicit) (3.6.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/site-packages (from implicit) (4.67.1)
Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.10/site-packages (from implicit) (1.15.3)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.10/site-packages (from implicit) (2.0.2)
Installing collected packages: implicit
Successfully installed implicit-0.7.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: scipy in /usr/local/lib/python3.10/site-packages (1.15.3)
Requirement already satisfied: numpy<2.5,>=1.23.5 in /usr/local/lib/python3.10/site-packages (from scipy) (2.0.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [113]:
import implicit
from scipy.sparse import coo_matrix

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [118]:
coshen= ['Id',
 'TotalPrice',
 'searchRoute',
 'corporateTariffCode',
 'profileId',
 'companyID',
 'legs0_duration',
 'legs1_duration',
 'legs0_segments0_seatsAvailable',
 'legs0_segments1_seatsAvailable',
 'legs1_segments0_seatsAvailable',
 'legs1_segments1_seatsAvailable',
 'miniRules0_monetaryAmount',
 'miniRules0_statusInfos',
 'miniRules1_monetaryAmount',
 'miniRules1_statusInfos',
 'pricingInfo_isAccessTP',
 'pricingInfo_passengerCount',
 'legs0_segments0_baggageAllowance_quantity',
 'legs0_segments1_baggageAllowance_quantity',
 'legs1_segments0_baggageAllowance_quantity',
 'legs1_segments1_baggageAllowance_quantity',
 'legs0_segments0_arrivalTo_airport_iata',
 'legs0_segments1_arrivalTo_airport_iata',
 'legs1_segments0_arrivalTo_airport_iata',
 'legs1_segments1_arrivalTo_airport_iata',
 'legs0_segments0_arrivalTo_airport_city_iata',
 'legs0_segments1_arrivalTo_airport_city_iata',
 'legs1_segments0_arrivalTo_airport_city_iata',
 'legs1_segments1_arrivalTo_airport_city_iata']

In [134]:
interactions = dft.select(['Id',"ranker_id", 'TotalPrice',
 'searchRoute',
 'corporateTariffCode',
 'profileId',
 'companyID',
 'legs0_duration',
 'legs1_duration',
 'legs0_segments0_seatsAvailable',
 'legs0_segments1_seatsAvailable',
 'legs1_segments0_seatsAvailable',
 'legs1_segments1_seatsAvailable',
 'miniRules0_monetaryAmount',
 'miniRules0_statusInfos',
 'miniRules1_monetaryAmount',
 'miniRules1_statusInfos',
 'pricingInfo_isAccessTP',
 'pricingInfo_passengerCount',
 'legs0_segments0_baggageAllowance_quantity',
 'legs0_segments1_baggageAllowance_quantity',
 'legs1_segments0_baggageAllowance_quantity',
 'legs1_segments1_baggageAllowance_quantity',
 'legs0_segments0_arrivalTo_airport_iata',
 'legs0_segments1_arrivalTo_airport_iata',
 'legs1_segments0_arrivalTo_airport_iata',
 'legs1_segments1_arrivalTo_airport_iata',
 'legs0_segments0_arrivalTo_airport_city_iata',
 'legs0_segments1_arrivalTo_airport_city_iata',
 'legs1_segments0_arrivalTo_airport_city_iata',
 'legs1_segments1_arrivalTo_airport_city_iata'])

# Map ranker_id and Id to integer indices
user_mapping = {u: i for i, u in enumerate(interactions["ranker_id"].unique())}
item_mapping = {f: i for i, f in enumerate(interactions["Id"].unique())}
interactions = interactions.with_columns([
    pl.col("ranker_id").replace(user_mapping).alias("user_idx"),
    pl.col("Id").replace(item_mapping).alias("item_idx")
])

In [137]:
user_idx_np = interactions["user_idx"].to_numpy().astype(np.int64)
item_idx_np = interactions["item_idx"].to_numpy().astype(np.int64)


feedback_np = np.ones(len(user_idx_np), dtype=np.float64)

In [138]:
matrix_shape = (int(user_idx_np.max()) + 1, int(item_idx_np.max()) + 1)
matrix = coo_matrix((feedback_np, (user_idx_np, item_idx_np)), shape=matrix_shape, dtype=np.float64)

In [139]:
# Train ALS matrix factorization
model = implicit.als.AlternatingLeastSquares(factors=64, regularization=0.1, iterations=20)
model.fit(matrix)

/usr/local/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 64 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
/usr/local/lib/python3.10/site-packages/implicit/utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.16300559043884277 seconds
  warnings.warn(
100%|██████████| 20/20 [34:06<00:00, 102.30s/it]

In [140]:
import joblib
#Save the model
joblib.dump(model, '/kaggle/working/my_als_model.pkl')

['/kaggle/working/my_als_model.pkl']

In [141]:
# Predict scores for test set
user_idx = dftt["ranker_id"].replace(user_mapping, default=-1).cast(pl.Int64).to_numpy()
item_idx = dftt["Id"].replace(item_mapping, default=-1).cast(pl.Int64).to_numpy()

# Ensure test indices are numpy int64
user_idx = user_idx.astype(np.int64)
item_idx = item_idx.astype(np.int64)

/tmp/ipykernel_10/1714603886.py:2: DeprecationWarning: the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)
  user_idx = dftt["ranker_id"].replace(user_mapping, default=-1).cast(pl.Int64).to_numpy()
/tmp/ipykernel_10/1714603886.py:3: DeprecationWarning: the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)
  item_idx = dftt["Id"].replace(item_mapping, default=-1).cast(pl.Int64).to_numpy()

In [142]:
y_pred = []
for u, i in zip(user_idx, item_idx):
    if u == -1 or i == -1:   # cold start
        y_pred.append(0.0)
    else:
        y_pred.append(float(model.user_factors[u] @ model.item_factors[i]))

dftt = dftt.with_columns(pl.Series("score", y_pred))

In [147]:
submission = (
    dftt.with_columns(
        pl.col("score")
        .rank(method="ordinal", descending=True)
        .over("ranker_id")
        .cast(pl.Int64)
        .alias("selected")
    )
    .select(["Id", "ranker_id", "selected"])
)

# Save submission file
submission.write_csv("/kaggle/working/submission.csv")

In [148]:
import  pandas as pd
z = pd.read_csv('/kaggle/working/submission.csv')
z.shape
z.head(20)

          Id  ranker_id  selected
0   18144679       2928         1
1   18144680       2928         2
2   18144681       2928         3
3   18144682       2928         4
4   18144683       2928         5
5   18144684       2928         6
6   18144685       2928         7
7   18144686       2928         8
8   18144687       2928         9
9   18144688       2928        10
10  18144689       2928        11
11  18144690       2928        12
12  18144691       2928        13
13  18144692       2928        14
14  18144693       2928        15
15  18144694       2928        16
16  18144695       2928        17
17  18144696       2928        18
18  18144697       2928        19
19  18144698       2928        20